postgresql jdbc driver updated to latest 42.2.9 - fixes problem on postgresql 11.5
problem appeared on PostgreSQL 11.5 (Debian 11.5-1+deb10u1):
org.postgresql.util.PSQLException: Transaction isolation level 4 not supported.
  at org.postgresql.jdbc2.AbstractJdbc2Connection.setTransactionIsolation(AbstractJdbc2Connection.java:955)
  at com.exedio.cope.ConnectionFactory.createRaw(ConnectionFactory.java:80)
  at com.exedio.cope.ConnectionFactory.create(ConnectionFactory.java:63)