CopyConstraintsForSetFields: fix SetFieldCopyTest on Oracle
fixes:
  Doing runtime.test for ora-sq
  Testcase: addToUnorderedItems(com.exedio.cope.pattern.SetFieldCopyTest):	Caused an ERROR
  duplicate constraint name in table ParenInCatal_elemSameCata: PareInCata_elSamCat_ca_MN
  java.lang.RuntimeException: duplicate constraint name in table ParenInCatal_elemSameCata: PareInCata_elSamCat_ca_MN
     at com.exedio.dsmf.Table.register(Table.java:113)
     at com.exedio.dsmf.Constraint.<init>(Constraint.java:69)
     at com.exedio.dsmf.CheckConstraint.<init>(CheckConstraint.java:57)
     at com.exedio.dsmf.CheckConstraint.<init>(CheckConstraint.java:35)
     at com.exedio.dsmf.Column.newCheck(Column.java:94)
     at com.exedio.cope.Column.newCheck(Column.java:70)
     at com.exedio.cope.IntegerColumn.makeSchema(IntegerColumn.java:162)
     at com.exedio.cope.ItemColumn.makeSchema(ItemColumn.java:53)
     at com.exedio.cope.Column.makeSchema(Column.java:102)
     at com.exedio.cope.Table.makeSchema(Table.java:232)
     at com.exedio.cope.Database.makeSchema(Database.java:513)
     at com.exedio.cope.Database.createSchema(Database.java:114)
     at com.exedio.cope.Connect.createSchema(Connect.java:166)
     at com.exedio.cope.Model.createSchema(Model.java:374)