move instrument.*Getter implementations to top-level
Otherwise Class#getCanonicalName() requires instrumentor annotations at runtime.
Actually getCanonicalName on Dispatcher.Result.class did throw NoClassDefFoundError for BooleanGetter.class.