WrapLiteralFeature/Item added, tests problem in openjdk-23.0.2
instrument.test.srcinstrument:
instrument parameter timestampFile is deprecated - no longer required
[instrument] Instrumenting in verify mode.
[instrument] compile error in interim code - writing to /var/lib/jenkins/workspace/cope_variant-Jdk-Latest-AllDB/build/instrument/instrument.test.srcinstrument/interimsrc for review
[instrument] line numbers in errors below are in interim code, not in original code
[instrument] error: /com/exedio/cope/instrument/testmodel/WrapLiteralItem.java:11: error: empty character literal
[instrument]        static final  WrapLiteralFeature singleQuoteChar=new WrapLiteralFeature(''');
[instrument]                                                                                ^
[instrument] error: /com/exedio/cope/instrument/testmodel/WrapLiteralItem.java:19: error: reached end of file while parsing
[instrument] 2 errors