dsmf.Dialect verifies tables ordered by name, make it deterministic for more than one unused table
fixes test failure on MySQL 8.0:
expected: <[ItemB, ItemA, ItemA_this_Seq]> but was: <[ItemB, ItemA_this_Seq, ItemA]>
	at com.exedio.cope.SchemaMismatchTableNameTest.testIt(SchemaMismatchTableNameTest.java:101)