network tests fixed
Tests did suddenly start to fail with #11450 (02.02.2024, 13:27:31).
Last successful build was #11449 (10.01.2024, 15:39:43).

Main / com.exedio.cope.ClusterNetworkChangeListenerTest.testMulticast()
java.lang.RuntimeException: 14446
	at com.exedio.cope.ClusterProperties.newListenSocket(ClusterProperties.java:374)
	at com.exedio.cope.ClusterListenerMulticast.<init>(ClusterListenerMulticast.java:60)
	at com.exedio.cope.Cluster.<init>(Cluster.java:39)
	at com.exedio.cope.Connect.<init>(Connect.java:127)
	at com.exedio.cope.Model.connect(Model.java:154)
	at com.exedio.cope.ClusterNetworkChangeListenerTest.testMulticast(ClusterNetworkChangeListenerTest.java:55)
Caused by: java.net.SocketException: No such device
	at java.base/java.net.PlainDatagramSocketImpl.join(Native Method)
	at java.base/java.net.AbstractPlainDatagramSocketImpl.joinGroup(AbstractPlainDatagramSocketImpl.java:259)
	at java.base/java.net.MulticastSocket.joinGroup(MulticastSocket.java:412)
	at com.exedio.cope.ClusterProperties.newListenSocket(ClusterProperties.java:355)
	... 48 more

Main / com.exedio.cope.ClusterNetworkPingTest.testMulticast()
java.lang.RuntimeException: 14446
	at com.exedio.cope.ClusterProperties.newListenSocket(ClusterProperties.java:374)
	at com.exedio.cope.ClusterListenerMulticast.<init>(ClusterListenerMulticast.java:60)
	at com.exedio.cope.Cluster.<init>(Cluster.java:39)
	at com.exedio.cope.Connect.<init>(Connect.java:127)
	at com.exedio.cope.Model.connect(Model.java:154)
	at com.exedio.cope.ClusterNetworkPingTest.testMulticast(ClusterNetworkPingTest.java:77)
Caused by: java.net.SocketException: No such device
	at java.base/java.net.PlainDatagramSocketImpl.join(Native Method)
	at java.base/java.net.AbstractPlainDatagramSocketImpl.joinGroup(AbstractPlainDatagramSocketImpl.java:259)
	at java.base/java.net.MulticastSocket.joinGroup(MulticastSocket.java:412)
	at com.exedio.cope.ClusterProperties.newListenSocket(ClusterProperties.java:355)
	... 48 more

Main / com.exedio.cope.ClusterNetworkPing3Test.testMulticast(
java.lang.RuntimeException: 14446
	at com.exedio.cope.ClusterProperties.newListenSocket(ClusterProperties.java:374)
	at com.exedio.cope.ClusterListenerMulticast.<init>(ClusterListenerMulticast.java:60)
	at com.exedio.cope.Cluster.<init>(Cluster.java:39)
	at com.exedio.cope.Connect.<init>(Connect.java:127)
	at com.exedio.cope.Model.connect(Model.java:154)
	at com.exedio.cope.ClusterNetworkPing3Test.testMulticast(ClusterNetworkPing3Test.java:55)
Caused by: java.net.SocketException: No such device
	at java.base/java.net.PlainDatagramSocketImpl.join(Native Method)
	at java.base/java.net.AbstractPlainDatagramSocketImpl.joinGroup(AbstractPlainDatagramSocketImpl.java:259)
	at java.base/java.net.MulticastSocket.joinGroup(MulticastSocket.java:412)
	at com.exedio.cope.ClusterProperties.newListenSocket(ClusterProperties.java:355)
	... 48 more

Main / com.exedio.cope.ClusterPropertiesTest.testOk()
java.lang.RuntimeException: 14446
	at com.exedio.cope.ClusterProperties.newListenSocket(ClusterProperties.java:374)
	at com.exedio.cope.ClusterListenerMulticast.<init>(ClusterListenerMulticast.java:60)
	at com.exedio.cope.Cluster.<init>(Cluster.java:39)
	at com.exedio.cope.Connect.<init>(Connect.java:127)
	at com.exedio.cope.Model.connect(Model.java:154)
	at com.exedio.cope.ClusterPropertiesTest.testOk(ClusterPropertiesTest.java:64)
Caused by: java.net.SocketException: No such device
	at java.base/java.net.PlainDatagramSocketImpl.join(Native Method)
	at java.base/java.net.AbstractPlainDatagramSocketImpl.joinGroup(AbstractPlainDatagramSocketImpl.java:259)
	at java.base/java.net.MulticastSocket.joinGroup(MulticastSocket.java:412)
	at com.exedio.cope.ClusterProperties.newListenSocket(ClusterProperties.java:355)
	... 48 more

Main / com.exedio.cope.ClusterPropertiesTest.testCustomSinglecast(
java.lang.RuntimeException: 14446
	at com.exedio.cope.ClusterProperties.newListenSocket(ClusterProperties.java:374)
	at com.exedio.cope.ClusterListenerMulticast.<init>(ClusterListenerMulticast.java:60)
	at com.exedio.cope.Cluster.<init>(Cluster.java:39)
	at com.exedio.cope.Connect.<init>(Connect.java:127)
	at com.exedio.cope.Model.connect(Model.java:154)
	at com.exedio.cope.ClusterPropertiesTest.testCustomSinglecast(ClusterPropertiesTest.java:247)
Caused by: java.net.BindException: Address already in use (Bind failed)
	at java.base/java.net.PlainDatagramSocketImpl.bind0(Native Method)
	at java.base/java.net.AbstractPlainDatagramSocketImpl.bind(AbstractPlainDatagramSocketImpl.java:135)
	at java.base/java.net.DatagramSocket.bind(DatagramSocket.java:394)
	at java.base/java.net.DatagramSocket.<init>(DatagramSocket.java:244)
	at java.base/java.net.DatagramSocket.<init>(DatagramSocket.java:301)
	at java.base/java.net.DatagramSocket.<init>(DatagramSocket.java:273)
	at com.exedio.cope.ClusterProperties.newListenSocket(ClusterProperties.java:360)
	... 48 more

Main / com.exedio.cope.ClusterPropertiesTest.testCustomMulticast()
java.lang.RuntimeException: 14446
	at com.exedio.cope.ClusterProperties.newListenSocket(ClusterProperties.java:374)
	at com.exedio.cope.ClusterListenerMulticast.<init>(ClusterListenerMulticast.java:60)
	at com.exedio.cope.Cluster.<init>(Cluster.java:39)
	at com.exedio.cope.Connect.<init>(Connect.java:127)
	at com.exedio.cope.Model.connect(Model.java:154)
	at com.exedio.cope.ClusterPropertiesTest.testCustomMulticast(ClusterPropertiesTest.java:197)
Caused by: java.net.SocketException: No such device
	at java.base/java.net.PlainDatagramSocketImpl.join(Native Method)
	at java.base/java.net.AbstractPlainDatagramSocketImpl.joinGroup(AbstractPlainDatagramSocketImpl.java:259)
	at java.base/java.net.MulticastSocket.joinGroup(MulticastSocket.java:412)
	at com.exedio.cope.ClusterProperties.newListenSocket(ClusterProperties.java:355)
	... 48 more

Main / com.exedio.cope.ClusterSenderMulticastTest.testIt()
java.io.IOException: Network is unreachable
	at java.base/java.net.PlainDatagramSocketImpl.send0(Native Method)
	at java.base/java.net.AbstractPlainDatagramSocketImpl.send(AbstractPlainDatagramSocketImpl.java:155)
	at java.base/java.net.DatagramSocket.send(DatagramSocket.java:695)
	at com.exedio.cope.ClusterSenderMulticast.send(ClusterSenderMulticast.java:84)
	at com.exedio.cope.ClusterSenderMulticastTest.testIt(ClusterSenderMulticastTest.java:55)

Main / com.exedio.cope.LoopbackTest.testNewDefaultSet() (and all other tests in this class)
java.net.SocketException: No such device
	at java.base/java.net.PlainDatagramSocketImpl.join(Native Method)
	at java.base/java.net.AbstractPlainDatagramSocketImpl.joinGroup(AbstractPlainDatagramSocketImpl.java:259)
	at java.base/java.net.MulticastSocket.joinGroup(MulticastSocket.java:412)
	at com.exedio.cope.LoopbackTest.testNewDefaultSet(LoopbackTest.java:80)