<tt> converted to {@code, prepares jdk 11.0.1
fails with:
error: tag not supported in the generated HTML version: tt

omitted @Wrap, runtime/testsrc, runtime/servlettestsrc, instrument/testsrc

for i in `find . -name "*.java"`; do sed -e 's/<tt>\(.*\)<\/tt>/\{\@code \1}/g' < $i > $i.sed; mv $i.sed $i; done