travis-ci: openjdk11 dropped
Needed since commit:
73c3b21a1c796afcb1866eb3ea130075756daef4
Tue Jun 29 17:28:56 2021 +0200
Dockerfiles bump distro versions

Otherwise fails:
    [junit] Failures (3):
    [junit]   JUnit Jupiter:InvalidPlainTextExceptionTest:testMessageNull()
    [junit]     MethodSource [className = 'com.exedio.cope.pattern.InvalidPlainTextExceptionTest', methodName = 'testMessageNull', methodParameterTypes = '']
    [junit]     => org.opentest4j.AssertionFailedError: expected: <3740> but was: <3739>
    [junit]        org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:54)
    [junit]        org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:195)
    [junit]        org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:152)
    [junit]        org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:147)
    [junit]        org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:327)
    [junit]        com.exedio.cope.tojunit.Assert.reserialize(Assert.java:290)
    [junit]        com.exedio.cope.pattern.InvalidPlainTextExceptionTest.testMessageNull(InvalidPlainTextExceptionTest.java:57)
    [junit]        java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [junit]        java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    [junit]        java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [junit]        [...]
    [junit]   JUnit Jupiter:InvalidPlainTextExceptionTest:testPlainTextNull()
    [junit]     MethodSource [className = 'com.exedio.cope.pattern.InvalidPlainTextExceptionTest', methodName = 'testPlainTextNull', methodParameterTypes = '']
    [junit]     => org.opentest4j.AssertionFailedError: expected: <3751> but was: <3750>
    [junit]        org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:54)
    [junit]        org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:195)
    [junit]        org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:152)
    [junit]        org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:147)
    [junit]        org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:327)
    [junit]        com.exedio.cope.tojunit.Assert.reserialize(Assert.java:290)
    [junit]        com.exedio.cope.pattern.InvalidPlainTextExceptionTest.testPlainTextNull(InvalidPlainTextExceptionTest.java:74)
    [junit]        java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [junit]        java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    [junit]        java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [junit]        [...]
    [junit]   JUnit Jupiter:InvalidPlainTextExceptionTest:testNormal()
    [junit]     MethodSource [className = 'com.exedio.cope.pattern.InvalidPlainTextExceptionTest', methodName = 'testNormal', methodParameterTypes = '']
    [junit]     => org.opentest4j.AssertionFailedError: expected: <3744> but was: <3743>
    [junit]        org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:54)
    [junit]        org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:195)
    [junit]        org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:152)
    [junit]        org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:147)
    [junit]        org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:327)
    [junit]        com.exedio.cope.tojunit.Assert.reserialize(Assert.java:290)
    [junit]        com.exedio.cope.pattern.InvalidPlainTextExceptionTest.testNormal(InvalidPlainTextExceptionTest.java:40)
    [junit]        java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [junit]        java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    [junit]        java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [junit]        [...]