DialectUrlMapper services file fixed in classes/runtime/dialects
caused failure of large numbers of tests on Windows:
IllegalPropertiesException: property dialect in ...utiltest.properties must be specified as there is no default