Postgresql 15.6 available on Debian bookworm
https://packages.debian.org/search?suite=bookworm&searchon=names&keywords=postgresql

Without test_db_user_public env pg-public fails with:

  org.postgresql.util.PSQLException: ERROR: permission denied for schema public

because:
  https://www.postgresql.org/about/news/postgresql-15-released-2526/
  PostgreSQL 15 also revokes the CREATE permission from all users except a
  database owner from the public (or default) schema.