mysql-connector-java updated to 8.0.29
affected are 8.0.26 and prior: https://nvd.nist.gov/vuln/detail/CVE-2021-2471
affected are 8.0.27 and prior: https://nvd.nist.gov/vuln/detail/CVE-2022-21363

max_allowed_packet must be increased because otherwise mysql tests do fail:

com.exedio.dsmf.SQLRuntimeException: INSERT INTO `SchemaTypeStringItem_fMax`(`this`,`element`)VALUES(?3?,?'跥跦跧跨跩跪跥跦跧跨跩跪跥跦跧跨跩跪跥跦跧跨跩跪跥跦跧跨跩跪跥跦跧跨跩跪跥跦跧跨跩跪跥跦跧跨跩跪跥跦跧跨跩跪跥跦跧跨跩跪跥跦跧跨跩跪跥跦跧跨跩跪跥跦跧跨跩跪跥跦跧跨跩跪跥跦跧跨跩跪跥跦跧跨跩跪跥跦跧跨 ... 跩跪跥跦跧跨跩跪跥跦跧跨跩跪跥跦跧跨跩跪' (truncated, was 15000000 characters)?)
  at com.exedio.cope.Executor.update(Executor.java:237)
  at com.exedio.cope.Executor.updateStrict(Executor.java:198)
  at com.exedio.cope.Database.store(Database.java:484)
  at com.exedio.cope.Database.store(Database.java:345)
  at com.exedio.cope.CreatedState.write(CreatedState.java:73)
  at com.exedio.cope.Entity.write(Entity.java:73)
  at com.exedio.cope.Item.doCreate(Item.java:195)
  at com.exedio.cope.Type.newItem(Type.java:989)
  at com.exedio.cope.SchemaTypeStringField.add(SchemaTypeStringField.java:82)
  at com.exedio.cope.SchemaTypeStringTest.testValues(SchemaTypeStringTest.java:152)
  ...
Caused by: com.mysql.cj.jdbc.exceptions.PacketTooBigException: Packet for query is too large (90,000,071 > 64,000,000). You can change this value on the server by setting the 'max_allowed_packet' variable.
  at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:107)
  at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
  at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1061)
  at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1009)
  at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1320)
  at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:994)
  at com.exedio.cope.Executor.update(Executor.java:232)
  ... 52 more