Jenkinsfile[Jdk11] use distinct port/multicastAddress again
Partially revert "Jenkinsfile[Jdk11] use docker" commit 3138ea271606e0f2ad65cb5c769c1182a7800d60.

Will fix sporadic failures in tests:

org.opentest4j.AssertionFailedError: expected: not <null>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:38)
	at org.junit.jupiter.api.Assertions.fail(Assertions.java:84)
	at org.junit.jupiter.api.AssertNotNull.failNull(AssertNotNull.java:47)
	at org.junit.jupiter.api.AssertNotNull.assertNotNull(AssertNotNull.java:36)
	at org.junit.jupiter.api.AssertNotNull.assertNotNull(AssertNotNull.java:31)
	at org.junit.jupiter.api.Assertions.assertNotNull(Assertions.java:258)
	at com.exedio.cope.ClusterNetworkChangeListenerTest$MockListener.assertRemote(ClusterNetworkChangeListenerTest.java:169)
	at com.exedio.cope.ClusterNetworkChangeListenerTest.test(ClusterNetworkChangeListenerTest.java:91)
	at com.exedio.cope.ClusterNetworkChangeListenerTest.testSinglecast(ClusterNetworkChangeListenerTest.java:73)

org.opentest4j.AssertionFailedError: expected: not <null>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:38)
	at org.junit.jupiter.api.Assertions.fail(Assertions.java:84)
	at org.junit.jupiter.api.AssertNotNull.failNull(AssertNotNull.java:47)
	at org.junit.jupiter.api.AssertNotNull.assertNotNull(AssertNotNull.java:36)
	at org.junit.jupiter.api.AssertNotNull.assertNotNull(AssertNotNull.java:31)
	at org.junit.jupiter.api.Assertions.assertNotNull(Assertions.java:258)
	at com.exedio.cope.ClusterNetworkChangeListenerTest$MockListener.assertRemote(ClusterNetworkChangeListenerTest.java:169)
	at com.exedio.cope.ClusterNetworkChangeListenerTest.test(ClusterNetworkChangeListenerTest.java:91)
	at com.exedio.cope.ClusterNetworkChangeListenerTest.testMulticast(ClusterNetworkChangeListenerTest.java:61)

org.opentest4j.AssertionFailedError: expected: not <null>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:38)
	at org.junit.jupiter.api.Assertions.fail(Assertions.java:84)
	at org.junit.jupiter.api.AssertNotNull.failNull(AssertNotNull.java:47)
	at org.junit.jupiter.api.AssertNotNull.assertNotNull(AssertNotNull.java:36)
	at org.junit.jupiter.api.AssertNotNull.assertNotNull(AssertNotNull.java:31)
	at org.junit.jupiter.api.Assertions.assertNotNull(Assertions.java:258)
	at com.exedio.cope.ClusterNetworkChangeListenerTest$MockListener.assertRemote(ClusterNetworkChangeListenerTest.java:169)
	at com.exedio.cope.ClusterNetworkChangeListenerTest.test(ClusterNetworkChangeListenerTest.java:91)
	at com.exedio.cope.ClusterNetworkChangeListenerTest.testSinglecast(ClusterNetworkChangeListenerTest.java:73)

org.opentest4j.AssertionFailedError: expected: <0> but was: <1>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:54)
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:195)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:168)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:163)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:349)
	at com.exedio.cope.ClusterNetworkPingTest.assertIt(ClusterNetworkPingTest.java:175)
	at com.exedio.cope.ClusterNetworkPingTest.assertIt(ClusterNetworkPingTest.java:137)
	at com.exedio.cope.ClusterNetworkPingTest.test(ClusterNetworkPingTest.java:108)
	at com.exedio.cope.ClusterNetworkPingTest.testSinglecast(ClusterNetworkPingTest.java:95)

org.opentest4j.AssertionFailedError: expected: <1.0> but was: <0.0>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:54)
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:195)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:72)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:67)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:451)
	at com.exedio.cope.ClusterNetworkPingTest.assertIt(ClusterNetworkPingTest.java:178)
	at com.exedio.cope.ClusterNetworkPingTest.assertIt(ClusterNetworkPingTest.java:137)
	at com.exedio.cope.ClusterNetworkPingTest.test(ClusterNetworkPingTest.java:112)
	at com.exedio.cope.ClusterNetworkPingTest.testMulticast(ClusterNetworkPingTest.java:80)

org.opentest4j.AssertionFailedError: expected: <0> but was: <1>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:54)
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:195)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:168)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:163)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:349)
	at com.exedio.cope.ClusterNetworkPing3Test.assertIt(ClusterNetworkPing3Test.java:206)
	at com.exedio.cope.ClusterNetworkPing3Test.assertIt(ClusterNetworkPing3Test.java:138)
	at com.exedio.cope.ClusterNetworkPing3Test.test(ClusterNetworkPing3Test.java:95)
	at com.exedio.cope.ClusterNetworkPing3Test.testMulticast(ClusterNetworkPing3Test.java:62)

org.opentest4j.AssertionFailedError: expected: <0> but was: <1>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:54)
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:195)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:168)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:163)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:349)
	at com.exedio.cope.ClusterNetworkPing3Test.assertIt(ClusterNetworkPing3Test.java:206)
	at com.exedio.cope.ClusterNetworkPing3Test.assertIt(ClusterNetworkPing3Test.java:138)
	at com.exedio.cope.ClusterNetworkPing3Test.test(ClusterNetworkPing3Test.java:95)
	at com.exedio.cope.ClusterNetworkPing3Test.testSinglecast(ClusterNetworkPing3Test.java:79)