instrument/annosrc excluded when running junit tests
related to
de14e8e7076b1b2c9dd2fb1bb982f6d22e211ad4
Fri Sep 2 15:37:28 2016 +0200

Otherwise Class#getCanonicalName() requires instrumentor annotations at runtime.
Actually getCanonicalName on Dispatcher.Result.class did throw NoClassDefFoundError for BooleanGetter.class.