Connection#isValid used in ConnectionFactory#isValidOnGet, requires ojdbc6
with ojdbc5 the following error occurs:
java.lang.AbstractMethodError: oracle.jdbc.driver.T4CConnection.isValid(I)Z